# Generated by Django 2.1.3 on 2021-04-13 07:04

import Core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedOccupancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Bed occupancy',
                'db_table': 'BedOccupancy',
            },
        ),
        migrations.CreateModel(
            name='BedOccupancyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('ward_name', models.CharField(max_length=255)),
                ('ward_id', models.IntegerField()),
                ('bed_occupancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.BedOccupancy')),
            ],
            options={
                'verbose_name_plural': 'Bed occupancyItems',
                'db_table': 'BedOccupancyItems',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseAtFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases at Facility',
                'db_table': 'DeathByDiseaseCaseAtFacility',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseAtFacilityItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=255)),
                ('ward_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('icd_10_code', models.CharField(max_length=255)),
                ('date_death_occurred', models.DateField()),
                ('death_by_disease_case_at_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.DeathByDiseaseCaseAtFacility')),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases at Facility Items',
                'db_table': 'DeathByDiseaseCaseAtFacilityItems',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseNotAtFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases Not at Facility',
                'db_table': 'DeathByDiseaseCaseNotAtFacility',
            },
        ),
        migrations.CreateModel(
            name='DeathByDiseaseCaseNotAtFacilityItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_death_id', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('icd_10_code', models.CharField(max_length=255)),
                ('date_death_occurred', models.DateField()),
                ('death_id', models.IntegerField()),
                ('death_by_disease_case_not_at_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.DeathByDiseaseCaseNotAtFacility')),
            ],
            options={
                'verbose_name_plural': 'Death by Disease Cases Not at Facility Items',
                'db_table': 'DeathByDiseaseCaseNotAtFacilityItems',
            },
        ),
        migrations.CreateModel(
            name='RevenueReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_trans_id', models.CharField(max_length=100)),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Revenue received',
                'db_table': 'RevenueReceived',
            },
        ),
        migrations.CreateModel(
            name='RevenueReceivedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_trans_id', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('patient_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('med_svc_code', models.CharField(max_length=50)),
                ('payer_id', models.CharField(max_length=50)),
                ('exemption_category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waived_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_provider_ranking_id', models.CharField(max_length=255)),
                ('revenue_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.RevenueReceived')),
            ],
            options={
                'verbose_name_plural': 'Revenue Received Items',
                'db_table': 'RevenueReceivedItems',
            },
        ),
        migrations.CreateModel(
            name='ServiceReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Services Received',
                'db_table': 'ServiceReceived',
            },
        ),
        migrations.CreateModel(
            name='ServiceReceivedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('med_svc_code', models.CharField(max_length=255)),
                ('icd_10_code', models.CharField(blank=True, max_length=255, null=True)),
                ('service_date', models.DateField()),
                ('service_provider_ranking_id', models.CharField(max_length=255)),
                ('visit_type', models.CharField(max_length=255)),
                ('service_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.ServiceReceived')),
            ],
            options={
                'verbose_name_plural': 'Services Received Items',
                'db_table': 'ServiceReceivedItems',
            },
        ),
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date_time', models.DateTimeField(auto_now=True)),
                ('failed_records', models.BigIntegerField()),
                ('passed_records', models.BigIntegerField()),
                ('payload', models.FileField(upload_to=Core.models.upload_image)),
                ('error_message', models.TextField()),
                ('facility_hfr_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Transactions summary',
                'db_table': 'TransactionSummary',
            },
        ),
    ]
