# Generated by Django 2.1.3 on 2021-04-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuereceived',
            name='system_trans_id',
        ),
    ]
