# Generated by Django 2.1.3 on 2021-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_revenuereceived_system_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='billed_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='revenuereceiveditems',
            name='waived_amount',
            field=models.IntegerField(),
        ),
    ]
