# Generated by Django 3.1.4 on 2021-01-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
