# Generated by Django 3.1.4 on 2021-01-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0002_auto_20210102_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmetadata',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
