# Generated by Django 3.1.4 on 2021-01-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0003_auto_20210120_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='hdrexemptioncategory',
            options={'verbose_name_plural': 'HDR Exemption Categories'},
        ),
        migrations.AlterModelOptions(
            name='hdrpayercategory',
            options={'verbose_name_plural': 'HDR Payer Categories'},
        ),
    ]
