# Generated by Django 3.1.4 on 2021-01-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0003_auto_20210102_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmetadata',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='eventmetadata',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='eventmetadata',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='eventmetadata',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='eventmetadata',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='eventmetadata',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventmetadata',
            name='server_version',
        ),
        migrations.AddField(
            model_name='eventmetadata',
            name='mediator_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventmetadata',
            name='open_him_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventmetadata',
            name='event_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
