# Generated by Django 3.1.4 on 2021-01-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0004_auto_20210102_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Facility',
            },
        ),
        migrations.AddField(
            model_name='ward',
            name='facility_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility'),
        ),
    ]
