# Generated by Django 3.1.4 on 2021-01-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0006_auto_20210105_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='department_id',
        ),
        migrations.AddField(
            model_name='ward',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.department'),
        ),
    ]
