# Generated by Django 3.1.4 on 2021-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0008_auto_20210111_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmetadata',
            name='open_him_client_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
