# Generated by Django 3.1.4 on 2021-01-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0009_clientmetadata_open_him_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='clientmetadata',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='clientmetadata',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_deleted',
        ),
    ]
