# Generated by Django 3.1.4 on 2021-01-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0010_auto_20210111_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='json',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
