# Generated by Django 3.1.4 on 2021-01-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0012_auto_20210111_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
