# Generated by Django 3.1.4 on 2021-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0013_auto_20210111_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='json',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='json',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
