# Generated by Django 3.1.4 on 2021-01-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0014_auto_20210111_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmetadata',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
