# Generated by Django 3.1.4 on 2021-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0015_auto_20210111_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemption',
            name='hdr_exemption_category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payer',
            name='hdr_payer_category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
